# Generated by Django 5.2.1 on 2025-05-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review_Model',
            new_name='Review',
        ),
    ]
